coverage:
    range: 85..95
    round: nearest
    precision: 2
    project:
      default:
        target: 95
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

comments: off
